plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.1'
    id 'io.spring.dependency-management' version '1.1.4'
}

group = 'com.simplechess'
version = '0.0.1'

// Ensure we're using Java 21
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.jfree:jfreechart:1.5.4'
    
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.junit.jupiter:junit-jupiter'
    
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
}

tasks.named('test') {
    useJUnitPlatform()
}

jar {
    archiveBaseName = 'simply-chess'
    archiveVersion = '0.0.1'
}

task stage(type: Copy, dependsOn: [clean, build]) {
    from jar.archiveFile
    into project.rootDir
    rename {
        'app.jar'
    }
}

stage.mustRunAfter(clean)

tasks.register('cleanAppJar', Delete) {
    delete 'app.jar'
}

clean.dependsOn cleanAppJar
